routes/web.php
<?php

use App\Models\User;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\QrController;
use App\Http\Controllers\testController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\KesehatanController;
use App\Http\Controllers\InventarisController;
use App\Http\Controllers\RekamMedisController;
use App\Http\Controllers\InventarisAlatController;
use App\Http\Controllers\InventarisObatController;
use App\Http\Controllers\API\InternalApiController;
use App\Http\Controllers\SuratManagementController;
use App\Http\Controllers\PetugasManagementController;
use App\Http\Controllers\BimbinganKonselingController;
use App\Http\Controllers\KaryawanManagementController;
use App\Http\Controllers\User\KesehatanUserController;
use App\Http\Controllers\User\KonselingUserController;
use App\Http\Controllers\MahasiswaManagementController;
use App\Http\Controllers\InventarisConsumableController;

/*
|--------------------------------------------------------------------------
| Peran Pengguna dan Hak Akses
|--------------------------------------------------------------------------
|
| Middleware untuk mengatur peran dan hak akses pengguna:
| - 'role:Admin'
| - 'role:Karyawan'
| - 'role:Dokter'
| - 'role:Psikolog,Perawat'
| - 'role:Mahasiswa'
|
| Middleware 'cdmi' memeriksa kelengkapan CDMI.
| Middleware 'dmti' memeriksa kelengkapan DMTI.
|
*/

// Route::view('/form/riwayat-pasien', 'kesehatan.form.riwayat-pasien')->name('riwayat-pasien');
// Route::view('/form/detail-rekam-medis', 'kesehatan.form.detail-rm')->name('detail-rm');
// keterangan berobat
// Route::view('/form/laporan-keterangan-berobat/buat-surat', 'kesehatan.form.laporan-keterangan-berobat.buat-surat')->name('lkb.buat-surat');
// Route::view('/form/laporan-keterangan-berobat/hasil-surat', 'kesehatan.form.laporan-keterangan-berobat.hasil-surat')->name('lkb.hasil-surat');

// Route::view('/form/laporan-keterangan-sakit/buat-surat', 'kesehatan.form.laporan-keterangan-sakit.buat-surat')->name('lks.buat-surat');
// Route::view('/form/laporan-keterangan-sakit/hasil-surat', 'kesehatan.form.laporan-keterangan-sakit.hasil-surat')->name('lks.hasil-surat');

// Route::view('/form/laporan-keterangan-rujukan/buat-surat', 'kesehatan.form.laporan-keterangan-rujukan.buat-surat')->name('lkr.buat-surat');
// Route::view('/form/laporan-keterangan-rujukan/hasil-surat', 'kesehatan.form.laporan-keterangan-rujukan.hasil-surat')->name('lkr.hasil-surat');

// Route::view('/form/laporan-keterangan-sehat/buat-surat', 'kesehatan.form.laporan-keterangan-sehat.buat-surat')->name('lkse.buat-surat');
// Route::view('/form/laporan-keterangan-sehat/hasil-surat', 'kesehatan.form.laporan-keterangan-sehat.hasil-surat')->name('lkse.hasil-surat');

// Route::view('/riwayat-kontrol', 'kesehatan.riwayat-kontrol')->name('riwayat-kontrol');

Route::get('/test', [testController::class, 'testprint']);


Route::middleware('guest')->group(function () {
    Route::redirect('/', '/login');
});

Route::middleware(['auth'])->group(function () {
    Route::redirect('/', '/profile');
    Route::prefix('profile')->name('profile.')->group(function () {
        Route::get('/', [ProfileController::class, 'edit'])->name('edit');
        Route::patch('/', [ProfileController::class, 'update'])->name('update');
        Route::delete('/', [ProfileController::class, 'destroy'])->name('destroy');

        Route::post('/update-avatar/{id}', [ProfileController::class, 'updateAvatar'])->name('update-avatar');
        Route::post('/create-rpd/{id}', [ProfileController::class, 'storeRPD'])->name('create-rpd');
        Route::patch('/update-dmti/{id}', [ProfileController::class, 'updateDMTI'])->name('update-dmti');
        Route::patch('/update-cdmi/{id}', [ProfileController::class, 'updateCDMI'])->name('update-cdmi');
    });

    // User routes ( Mahasiswa dan karyawan )
    Route::middleware('role:Mahasiswa,Karyawan')->group(function () {
        Route::prefix('user')->name('user.')->group(function () {
            Route::prefix('medical')->name('kesehatan.')->group(function () {
                // KesehatanUserController
                Route::get('/', [KesehatanUserController::class, 'dashboard'])->name('dashboard');
                // QrController
                Route::get('/kodeqr-kesehatan', [QrController::class, 'qrcode'])->name('kodeqr');

                Route::get('/riwayat-laporan', [KesehatanUserController::class, 'riwayatLaporan'])->name('riwayat-laporan');
                Route::get('/riwayat-laporan/surat-keterangan-berobat/{id}', [KesehatanUserController::class, 'showSuratKeteranganObat'])->name('surat-keterangan-berobat.show');
                Route::get('/riwayat-laporan/surat-keterangan-sehat/{id}', [KesehatanUserController::class, 'showSuratKeteranganSehat'])->name('surat-keterangan-sehat.show');
                Route::get('/riwayat-laporan/surat-keterangan-sakit/{id}', [KesehatanUserController::class, 'showSuratKeteranganSakit'])->name('surat-keterangan-sakit.show');
                Route::get('/riwayat-laporan/surat-rujukan/{id}', [KesehatanUserController::class, 'showSuratRujukan'])->name('surat-rujukan.show');

                Route::get('/print-laporan/surat-keterangan-berobat/{id}', [KesehatanUserController::class, 'printSuratKeteranganObat'])->name('surat-keterangan-berobat.print');
                Route::get('/print-laporan/surat-keterangan-sehat/{id}', [KesehatanUserController::class, 'printSuratKeteranganSehat'])->name('surat-keterangan-sehat.print');
                Route::get('/print-laporan/surat-keterangan-sakit/{id}', [KesehatanUserController::class, 'printSuratKeteranganSakit'])->name('surat-keterangan-sakit.print');
                Route::get('/print-laporan/surat-rujukan/{id}', [KesehatanUserController::class, 'printSuratRujukan'])->name('surat-rujukan.print');
            });
        });
    });

    // Mahasiswa routes KONSELING
    Route::middleware('role:Mahasiswa')->group(function () {
        Route::prefix('user')->name('user.')->group(function () {
            Route::prefix('konseling')->name('konseling.')->group(function () {
                Route::view('/', 'konseling.user.dashboard')->name('dashboard');

                Route::get('/kodeqr-bimbingan', [QrController::class, 'qrcodebimbingan'])->name('kodeqr-bimbingan');
                Route::get('/link-feedback', [KonselingUserController::class, 'linkfeedback'])->name('link-feedback');
                Route::get('/form-feedback/{id}/{token}', [KonselingUserController::class, 'formfeedback'])->name('form-feedback');
                Route::post('/form-feedback/store', [KonselingUserController::class, 'storefeedback'])->name('store-feedback');
                Route::get('/review-feedback-bimbingan/{id}', [KonselingUserController::class, 'reviewfeedback'])->name('review-feedback-bimbingan');

                Route::get('/kodeqr-konsultasi', [QrController::class, 'qrcodekonsultasi'])->name('kodeqr-konsultasi');
                Route::get('riwayat-konsultasi', [KonselingUserController::class, 'riwayatKonsultasi'])->name('riwayat-konsultasi');
                Route::get('riwayat-konsultasi/{id}', [KonselingUserController::class, 'detailKonsultasi'])->name('detail-konsultasi');
                Route::post('riwayat-konsultasi/filter', [KonselingUserController::class, 'filterKonsultasi'])->name('filter-konsultasi');
            });
        });
    });

    Route::middleware('role:Admin,Dokter,Psikolog,Perawat')->group(function () {
        // inventaris prefix route
        Route::prefix('inventaris')->name('inventaris.')->group(function () {
            Route::get('/', [DashboardController::class, 'inventaris'])->name('dashboard');
            Route::get('/pengaturan', [InventarisObatController::class, 'pengaturanInventaris'])->name('pengaturanInventaris');
            Route::post('/pengaturan/print', [InventarisObatController::class, 'printInventaris'])->name('printInventaris');
            // Kategori routes
            Route::prefix('kategori')->name('kategori.')->group(function () {
                Route::get('/obat/delete/{id}', [InventarisObatController::class, 'deleteKategori'])->name('obat.delete');
                Route::get('/alat/delete/{id}', [InventarisAlatController::class, 'deleteKategoriAlat'])->name('alat.delete');
                Route::get('/consumable/delete/{id}', [InventarisConsumableController::class, 'deleteKategoriTersisa'])->name('consumable.delete');

                Route::post('/obat/store', [InventarisObatController::class, 'storeKategori'])->name('obat.store');
                Route::post('/obat/update/{id}', [InventarisObatController::class, 'updateKategori'])->name('obat.update');

                Route::post('/alat/store', [InventarisAlatController::class, 'storeKategoriAlat'])->name('alat.store');
                Route::post('/alat/update/{id}', [InventarisAlatController::class, 'updateKategoriAlat'])->name('alat.update');

                Route::post('/consumable/store', [InventarisConsumableController::class, 'storeKategoriTersisa'])->name('consumable.store');
                Route::post('/consumable/update/{id}', [InventarisConsumableController::class, 'updateKategoriTersisa'])->name('consumable.update');
            });

            // Obat routes
            Route::prefix('obat')->name('obat.')->group(function () {
                Route::get('/', [InventarisObatController::class, 'index'])->name('index');
                Route::get('/{uuid}', [InventarisObatController::class, 'show'])->name('show');
                Route::get('/log/pengguna/{ulid}', [InventarisObatController::class, 'logPengguna'])->name('logpengguna');

                Route::post('/deposit/{uuid}', [InventarisObatController::class, 'deposit'])->name('deposit');
                Route::post('/store', [InventarisObatController::class, 'store'])->name('store');

app/Http/Controllers/KesehatanController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use App\Models\RekamMedis;
use App\Models\SuratRujukan;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Log;
use App\Models\SuratKeteranganSakit;
use App\Models\SuratKeteranganBerobat;
use App\Models\SuratKeteranganSehat;
use Illuminate\Support\Facades\Validator;
use Illuminate\Validation\ValidationException;

class KesehatanController extends Controller
{
    public function dashboard()
    {
        // mengambil pasien dengan role mahasiswa dan karyawan
        $user = User::all();
        $skb = SuratKeteranganBerobat::all()->count();
        $sks = SuratKeteranganSakit::all()->count();
        $sr = SuratRujukan::all()->count();
        $skse = SuratKeteranganSehat::all()->count();

        $sk = $skb + $sks + $sr + $skse;

        $rm = RekamMedis::all();

        $rmcount = $rm->count();

        // ambil rekam medis 5 terbaru
        $rm = $rm->sortByDesc('created_at')->take(5);

        $pasien = $user->where('role', 'Mahasiswa')->count() + $user->where('role', 'Karyawan')->count();
        $dokter = $user->where('role', 'Dokter')->count();
        return view('kesehatan.dashboard', compact('pasien', 'dokter', 'sk', 'rmcount', 'rm'));
    }

    public function dataKontrolPasien()
    {
        $data = User::with('PasienRM')
            ->whereIn('role', ['Mahasiswa', 'Karyawan'])
            // ->orWhere('role', 'Karyawan')
            ->orderByRaw('(SELECT COUNT(*) FROM rekam_medis WHERE rekam_medis.pasien_id = users.id) DESC')
            ->orderBy('name', 'asc')
            ->paginate(20);

        return view('kesehatan.data-kontrol-pasien', compact('data'));
    }

    public function filterDKP(Request $request)
    {
        try {
            $input = $request->all();

            $validatedData = Validator::make($input, [
                'filter' => 'nullable|string',
            ])->validate();

            $upperName = strtoupper($validatedData['filter'] ?? '');

            $query = User::with('PasienRM')
                ->whereIn('role', ['Mahasiswa', 'Karyawan']);
                // ->orWhere('role', 'Karyawan');

            if (!empty($upperName)) {
                $query->where(function ($query) use ($upperName) {
                    $query->whereRaw('UPPER(name) LIKE ?', ['%' . $upperName . '%'])
                        ->orWhereRaw('UPPER(email) LIKE ?', ['%' . $upperName . '%']);
                });
            }

            $query = $query->orderByRaw('(SELECT COUNT(*) FROM rekam_medis WHERE rekam_medis.pasien_id = users.id) DESC')
                ->orderBy('name', 'asc');

            $data = $query->paginate(20);

            $table = view('components.kesehatan.table-data-kontrol', compact('data'))->render();

            return response()->json(['table' => $table]);
        } catch (\Exception $th) {
            if ($th instanceof ValidationException) {
                return back()->withErrors($th->errors())->withInput()->with('error', 'Gagal memfilter User: ' . $th->getMessage());
            } else {
                Log::error('Gagal memfilter User: ' . $th->getMessage());
                return back()->with('error', 'Gagal memfilter User');
            }
        }
    }
}

resources/views/kesehatan/user/dashboard.blade.php
<x-app-layout>
    {{-- Content Header --}}
    <div class="flex items-center justify-between px-2 sm:px-4 py-3 lg:py-5 border-b dark:border-blue-800">
        <h1 class="text-2xl font-semibold">Kesehatan Overview</h1>
    </div>
    {{-- Main Content --}}
    <div class="px-2 sm:px-4 py-3 lg:py-5 border-b dark:border-blue-600">
        <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3 w-full">
            <div class="bg-white dark:bg-darker p-4 rounded-lg">
                <div class="text-sm mb-3 flex items-center">
                    <span class="icon-[solar--user-linear] me-2"></span>
                    Total Pasien
                </div>
                <span class="text-xl font-semibold">{{ $pasien }}</span>
                <div class="mt-3 text-xs text-yellow-400 font-light">Pasien terdaftar.</div>
            </div>
            <div class="bg-white dark:bg-darker p-4 rounded-lg">
                <div class="text-sm mb-3 flex items-center">
                    <span class="icon-[mdi--doctor] me-2"></span>
                    Total Dokter
                </div>
                <span class="text-xl font-semibold">{{ $dokter }}</span>
                <div class="mt-3 text-xs text-yellow-400">Dokter terdaftar.</div>
            </div>
            <div class="bg-white dark:bg-darker p-4 rounded-lg">
                <div class="flex justify-center items-center">
                    <div class="flex flex-col gap-1 text-center">
                        <div class="flex items-center justify-center">
                            @if (Auth::user()->avatar_url != null)
                                <img class="w-10 h-10 rounded-full"
                                    src="{{ asset('storage/images/' . Auth::user()->avatar_url) }}"
                                    alt="{{ Auth::user()->name }}" />
                            @else
                                <img class="w-10 h-10 rounded-full" :src="generateAvatar('{{ Auth::user()->email }}')"
                                    alt="{{ Auth::user()->name }}" />
                            @endif
                        </div>
                        <div class="flex flex-col">
                            <span class="font-semibold">{{ Auth::user()->name }}</span>
                            <span class="text-sm text-gray-700 dark:text-gray-300">{{ Auth::user()->role }}</span>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="px-2 sm:px-4 py-3 lg:py-5">
        <div class="flex flex-col md:flex-row gap-1">
            <div class="bg-white dark:bg-darker p-4 rounded-lg w-full">
                <div class="">Kesehatan Surat Overview</div>
                <div class="bg-gray-100 dark:bg-dark p-2 rounded-md mt-2">
                    <div class="w-full mt-1" style="width: 100%;">
                        <canvas id="surat" :class="{ 'dark': isDark }"></canvas>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="{{ asset('chartjs/dist/chart.umd.js') }}" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script type="module" src="{{ asset('src/js/kesehatan/dashboard-user.js') }}"></script>
</x-app-layout>

resources/views/kesehatan/user/detail-skb.blade.php
<x-app-layout>
    {{-- Content Header --}}
    <div class="px-2 sm:px-4 py-3 lg:py-5 border-b dark:border-blue-800">
        <h1 class="text-xl sm:text-2xl font-semibold">Surat Keterangan Berobat</h1>
        <span class="text-gray-700 dark:text-gray-300 text-sm mt-2">{{ $surat->nomor_surat }}</span>
    </div>
    {{-- Main Content --}}
    <div class="px-2 sm:px-4 py-3 lg:py-5">
        <div class="flex justify-center flex-col md:flex-row gap-2 max-w-screen-xl mx-auto">
            {{-- MEMBUAT SURAT --}}
            <div class="p-4 bg-white dark:bg-darker sm:rounded-lg w-full">
                <div class="w-full">
                    <section>
                        <header>
                            <h2 class="text-xl font-semibold text-gray-900 dark:text-gray-100">
                                Surat Keterangan Berobat (PDF)
                            </h2>
                        </header>
                        <div class="mt-3 bg-gray-100 dark:bg-dark p-3 rounded">
                            <div class="text-sm font-medium italic">
                                Yang bertanda tangan di bawah ini:
                            </div>
                            <div class="grid gap-2 md:grid-cols-2 mt-2">
                                <div>
                                    <x-input-label for="nama_dokter" :value="'Nama'" />
                                    <x-input-text id="nama_dokter" name="nama_dokter" type="text"
                                        class="mt-2 block w-full cursor-not-allowed" value="{{ $surat->nama_dokter }}"
                                        disabled readonly />
                                </div>
                                <div>
                                    <x-input-label for="jabatan_dokter" :value="'Jabatan'" />
                                    <x-input-text id="jabatan_dokter" name="jabatan_dokter" type="text"
                                        class="mt-2 block w-full cursor-not-allowed"
                                        value="{{ $surat->jabatan_dokter }}" disabled readonly />
                                </div>
                            </div>
                        </div>
                        <div class="mt-3 bg-gray-100 dark:bg-dark p-3 rounded">
                            <div class="text-sm font-medium italic">
                                Dengan ini menerangkan bahwa:
                            </div>
                            <div class="grid gap-2 md:grid-cols-2 mt-2">
                                <div>
                                    <x-input-label for="nik" :value="'NIK'" />
                                    <x-input-text id="nik" name="nik" type="number"
                                        class="mt-2 block w-full cursor-not-allowed" value="{{ $surat->nik }}"
                                        disabled readonly />
                                </div>
                                <div>
                                    <x-input-label for="nama_pasien" :value="'Nama'" />
                                    <x-input-text id="nama_pasien" name="nama_pasien" type="text"
                                        class="mt-2 block w-full cursor-not-allowed" value="{{ $surat->nama_pasien }}"
                                        disabled readonly />
                                </div>
                                <div>
                                    <x-input-label for="ttl" :value="'Tempat/tgl lahir'" />
                                    <x-input-text id="ttl" name="ttl" type="text"
                                        class="mt-2 block w-full cursor-not-allowed" value="{{ $surat->ttl }}"
                                        disabled readonly />
                                </div>
                                <div>
                                    <x-input-label for="jenis_kelamin" :value="'Jenis Kelamin'" />
                                    <x-input-text id="jenis_kelamin" name="jenis_kelamin" type="text"
                                        class="mt-2 block w-full cursor-not-allowed" value="{{ $surat->jenis_kelamin }}"
                                        disabled readonly />
                                </div>
                                <div>
                                    <x-input-label for="usia" :value="'Usia'" />
                                    <x-input-text id="usia" name="usia" type="number"
                                        class="mt-2 block w-full cursor-not-allowed" value="{{ $surat->usia }}"
                                        disabled readonly />
                                </div>
                                <div>
                                    <x-input-label for="no_hp" :value="'No. Handphone'" />
                                    <x-input-text id="no_hp" name="no_hp" type="number"
                                        class="mt-2 block w-full cursor-not-allowed" value="{{ $surat->no_hp }}"
                                        disabled readonly />
                                </div>
                            </div>
                            <div class="mt-3 text-sm">
                                <p>
                                    <?php \Carbon\Carbon::setLocale('id'); ?>
                                    Telah berobat di Klinik Polbangtan Malang pada hari
                                    <span>{{ \Carbon\Carbon::parse($surat->created_at)->translatedFormat('l') }}</span>
                                    tanggal <span
                                        id="datenow">{{ \Carbon\Carbon::parse($surat->created_at)->translatedFormat('d F Y') }}</span>
                                    dengan
                                    diagnosa <span class="uppercase">{{ $surat->diagnosa }}</span>
                                </p>
                                <br>
                                <p>
                                    Demikian surat keterangan ini kami buat dan dapat dipertanggung jawabkan
                                    sebagaimana mestinya.
                                </p>
                            </div>
                        </div>
                        <div class="mt-3 bg-green-100 dark:bg-green-800 p-3 rounded">
                            <p class="text-green-800 dark:text-green-100 text-sm">Tidak dapat melakukan perubahan pada
                                dokumen, Anda bisa meminta buat ulang kepada dokter untuk dokumen serupa.</p>
                        </div>
                        <form action="{{ route('user.kesehatan.surat-keterangan-berobat.print', $surat->id) }}"
                            class="flex gap-2 mt-3" method="get">
                            @csrf
                            <x-button class="py-2 px-4" type="submit">{{ __('Unduh Dokumen') }}</x-button>
                        </form>
                    </section>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/kesehatan/user/detail-sks.blade.php
<x-app-layout>
    {{-- Content Header --}}
    <div class="px-2 sm:px-4 py-3 lg:py-5 border-b dark:border-blue-800">
        <h1 class="text-xl sm:text-2xl font-semibold">Surat Keterangan Sakit</h1>
        <span class="text-gray-700 dark:text-gray-300 text-sm mt-2">{{ $surat->nomor_surat }}</span>
    </div>
    {{-- Main Content --}}
    <div class="px-2 sm:px-4 py-3 lg:py-5">
        <div class="flex justify-center flex-col md:flex-row gap-2 max-w-screen-xl mx-auto">
            {{-- MEMBUAT SURAT --}}
            <div class="p-4 bg-white dark:bg-darker sm:rounded-lg w-full">
                <div class="w-full">
                    <section>
                        <header>
                            <h2 class="text-xl font-semibold text-gray-900 dark:text-gray-100">
                                Surat Keterangan Sakit (PDF)
                            </h2>
                        </header>
                        <div class="mt-3 bg-gray-100 dark:bg-dark p-3 rounded">
                            <div class="text-sm font-medium italic">
                                Yang bertanda tangan dibawah ini menerangkan bahwa:
                            </div>
                            <div class="grid gap-2 md:grid-cols-2 mt-2">
                                <div>
                                    <x-input-label for="nik" :value="'NIK'" />
                                    <x-input-text id="nik" name="nik" type="number"
                                        class="mt-2 block w-full cursor-not-allowed" value="{{ $surat->nik }}"
                                        disabled readonly />
                                </div>
                                <div>
                                    <x-input-label for="nama_pasien" :value="'Nama'" />
                                    <x-input-text id="nama_pasien" name="nama_pasien" type="text"
                                        class="mt-2 block w-full cursor-not-allowed" value="{{ $surat->nama_pasien }}"
                                        disabled readonly />
                                </div>
                                <div>
                                    <x-input-label for="ttl" :value="'Tempat/tgl lahir'" />
                                    <x-input-text id="ttl" name="ttl" type="text"
                                        class="mt-2 block w-full cursor-not-allowed" value="{{ $surat->ttl }}"
                                        disabled readonly />
                                </div>
                                <div>
                                    <x-input-label for="jenis_kelamin" :value="'Jenis Kelamin'" />
                                    <x-input-text id="jenis_kelamin" name="jenis_kelamin" type="text"
                                        class="mt-2 block w-full cursor-not-allowed" value="{{ $surat->jenis_kelamin }}"
                                        disabled readonly />
                                </div>
                                <div>
                                    <x-input-label for="usia" :value="'Usia'" />
                                    <x-input-text id="usia" name="usia" type="number"
                                        class="mt-2 block w-full cursor-not-allowed" value="{{ $surat->usia }}"
                                        disabled readonly />
                                </div>
                                <div>
                                    <x-input-label for="no_hp" :value="'No. Handphone'" />
                                    <x-input-text id="no_hp" name="no_hp" type="number"
                                        class="mt-2 block w-full cursor-not-allowed" value="{{ $surat->no_hp }}"
                                        disabled readonly />
                                </div>
                            </div>
                            <div class="mt-3 text-sm">
                                <p>
                                    Karena sakit diberi istirahat selama {{ $surat->lama_sakit }} hari, mulai tanggal {{ \Carbon\Carbon::parse($surat->tanggal_mulai)->translatedFormat('d F Y') }} s/d {{ \Carbon\Carbon::parse($surat->tanggal_akhir)->translatedFormat('d F Y') }}.
                                </p>
                            </div>
                        </div>
                        <div class="mt-3 bg-green-100 dark:bg-green-800 p-3 rounded">
                            <p class="text-green-800 dark:text-green-100 text-sm">Tidak dapat melakukan perubahan pada dokumen, Anda bisa meminta buat ulang kepada dokter untuk dokumen serupa.</p>
                        </div>
                        <form action="{{ route('user.kesehatan.surat-keterangan-sakit.print', $surat->id) }}"
                            class="flex gap-2 mt-3" method="get">
                            @csrf
                            <x-button class="py-2 px-4" type="submit">{{ __('Unduh Dokumen') }}</x-button>
                        </form>
                    </section>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>